"""
Domain models and interfaces for device lifecycle and persistence.
"""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import List, Protocol
from uuid import UUID

from nexa.domain.correlation import ObservationConflict
from nexa.domain.device import DeviceRecord


class LifecycleEventType(Enum):
    """Strongly-typed classification of lifecycle transitions."""

    FIRST_SEEN = "first_seen"
    BECAME_PRESENT = "became_present"
    BECAME_UNSEEN = "became_unseen"
    CONFLICT_DETECTED = "conflict_detected"


@dataclass(frozen=True)
class LifecycleEvent:
    """Historical state transition for a device."""

    device_id: UUID
    event_type: LifecycleEventType
    timestamp: datetime
    description: str = ""


@dataclass(frozen=True)
class ScanTransactionEnvelope:
    """
    Complete persistence mutations generated by one lifecycle evaluation.
    Preserves strict causal ordering for degraded persistence retries.
    """

    scope_key: str
    records: List[DeviceRecord]
    conflicts: List[ObservationConflict]
    events: List[LifecycleEvent]
    timestamp: datetime


class DeviceRepository(Protocol):
    """
    Abstract persistence boundary explicitly decoupled from sqlite internals.
    """

    def save_scan_transaction(self, envelope: ScanTransactionEnvelope) -> None:
        """
        Persists a complete scan transaction envelope atomically.
        If this fails, an exception is raised, triggering rollback and degraded mode.
        """
        ...

    def get_record_by_id(self, device_id: str) -> DeviceRecord | None:
        """
        Retrieves a specific DeviceRecord by its UUID.
        """
        ...

    def get_records_by_scope(self, scope_key: str) -> List[DeviceRecord]:
        """
        Hydrates all active records for a specific scope.
        """
        ...

    def prune_stale_records(self, threshold: datetime) -> int:
        """
        Executes an atomic cascading delete for all UNSEEN records
        where last_observed_at < threshold.
        Returns the number of deleted records.
        """
        ...
